apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: sanchitbansal10/twitter_clone:configserver
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: configserver-np
  labels:
    app: configserver-np
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 30031
      name: configserver
  selector:
    app: configserver



# How to run this:
# Run the kubernetes service using kubectl apply -f configserver.yml
# This will run the service at 8888 within kubernetes and expose it to the system on 30031
# Check the service here: http://localhost:30031/user_services_app/default
# Since its a nodeport it exposes the service to the internet. You can get your machine ip using ifconfig command and just open ${ip}:30031 on any device and it will work....MAGIC
# WHen you run ifconfig it will list down lots of network things, the ip you are looking for is enp4s0
