apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
    matchLabels:
      app: configserver
  replicas: 1
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: sanchitbansal10/twitter_clone:configserver
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: configserver-np
  labels:
    app: configserver-np
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 30031
      name: configserver
  selector:
    app: configserver