#Taken from here: https://github.com/BitInit/eureka-on-kubernetes/blob/master/k8s-eureka-prod.yml
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  selector:
    matchLabels:
      app: eurekaserver
  replicas: 1
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: sanchitbansal10/twitter_clone:eureka_server
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-np
  labels:
    app: eurekaserver-np
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30039
      name: eurekaserver
  selector:
    app: eurekaserver


# Read configserver script to check how to run the service using kubectl and expose it for the internet
